name: twenty
description: An open-source Windows application designed to help you follow the 20-20-20 rule.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  audioplayers: ^6.0.0
  bloc: ^8.1.4
  clever_settings: ^0.1.2+1
  clever_settings_flutter: ^0.1.1+1
  fluent_ui: ^4.9.1
  fluentui_system_icons: ^1.1.258
  fluid_animations: ^1.0.0
  flutter:
    sdk: flutter
  flutter_acrylic: ^1.1.4
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  launch_at_startup: ^0.3.1
  local_notifier: ^0.1.6
  meta: ^1.15.0
  package_info_plus: ^8.0.2
  system_theme: ^3.0.0
  tray_manager: ^0.2.3
  window_manager: ^0.4.2

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  msix: ^3.16.8
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icon/
    - assets/audio/

msix_config:
  display_name: Twenty
  publisher_display_name: Ruben Gullatz
  identity_name: rubengullatz.twenty
  msix_version: 1.0.0.0
  logo_path: E:\projects\flutter\twenty\assets\icon\logo_large.png
